server:
  port: 8082

spring:
  application:
    name: ct-fraud-detection-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/healthcare
